### PR TITLE
add allowed-origins config

### PR DESCRIPTION
**Pull request by cap10morgan**
ALLOWED_ORIGINS env var and set via user-http-api/allowed-origins Consul value

### CODE REVIEW

**Comment by tie-rack** [comment]
Add to the README explaining this configuration, and that its special `:all` case that differs from the acceptable values for [the allow-origin interceptor](https://github.com/pedestal/pedestal/blob/0.4.0/service/src/io/pedestal/http/cors.clj#L55-L69) (and I suppose, that this value coming from edn disallows using a fn).

Otherwise, LGTM.

**Comment by cap10morgan** [comment]
@tie-rack Is this acceptable for the README addition? It specifies the allowed values of the env var:

## Configuration

* ALLOWED_ORIGINS
    * This env var controls the cross-origin resource sharing (CORS) settings.
    * It should either be set to `:all` or an EDN vector of allowed origins.
    * For example: `ALLOWED_ORIGINS=["foo.example.com" "bar.example.com"]`

**Comment by tie-rack** [comment]
it can be those, or that map described [here](https://github.com/pedestal/pedestal/blob/0.4.0/service/src/io/pedestal/http/cors.clj#L61-L69).

**Comment by cap10morgan** [comment]
@tie-rack OK, I'll add that too.

**Comment by tie-rack** [comment]
Great. LGTM

**Pull request merged**
